// soc_simple_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module soc_simple_mm_interconnect_1 (
		input  wire        PLL_50_150_outclk0_clk,                                      //                                    PLL_50_150_outclk0.clk
		input  wire        jtag_uart_pipeline_bridge_reset_reset_bridge_in_reset_reset, // jtag_uart_pipeline_bridge_reset_reset_bridge_in_reset.reset
		input  wire [2:0]  jtag_uart_pipeline_bridge_m0_address,                        //                          jtag_uart_pipeline_bridge_m0.address
		output wire        jtag_uart_pipeline_bridge_m0_waitrequest,                    //                                                      .waitrequest
		input  wire [0:0]  jtag_uart_pipeline_bridge_m0_burstcount,                     //                                                      .burstcount
		input  wire [3:0]  jtag_uart_pipeline_bridge_m0_byteenable,                     //                                                      .byteenable
		input  wire        jtag_uart_pipeline_bridge_m0_read,                           //                                                      .read
		output wire [31:0] jtag_uart_pipeline_bridge_m0_readdata,                       //                                                      .readdata
		output wire        jtag_uart_pipeline_bridge_m0_readdatavalid,                  //                                                      .readdatavalid
		input  wire        jtag_uart_pipeline_bridge_m0_write,                          //                                                      .write
		input  wire [31:0] jtag_uart_pipeline_bridge_m0_writedata,                      //                                                      .writedata
		input  wire        jtag_uart_pipeline_bridge_m0_debugaccess,                    //                                                      .debugaccess
		output wire [0:0]  jtag_uart_avalon_jtag_slave_address,                         //                           jtag_uart_avalon_jtag_slave.address
		output wire        jtag_uart_avalon_jtag_slave_write,                           //                                                      .write
		output wire        jtag_uart_avalon_jtag_slave_read,                            //                                                      .read
		input  wire [31:0] jtag_uart_avalon_jtag_slave_readdata,                        //                                                      .readdata
		output wire [31:0] jtag_uart_avalon_jtag_slave_writedata,                       //                                                      .writedata
		input  wire        jtag_uart_avalon_jtag_slave_waitrequest,                     //                                                      .waitrequest
		output wire        jtag_uart_avalon_jtag_slave_chipselect                       //                                                      .chipselect
	);

	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest;   // jtag_uart_avalon_jtag_slave_translator:uav_waitrequest -> jtag_uart_pipeline_bridge_m0_translator:uav_waitrequest
	wire  [31:0] jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata;      // jtag_uart_avalon_jtag_slave_translator:uav_readdata -> jtag_uart_pipeline_bridge_m0_translator:uav_readdata
	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess;   // jtag_uart_pipeline_bridge_m0_translator:uav_debugaccess -> jtag_uart_avalon_jtag_slave_translator:uav_debugaccess
	wire   [2:0] jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_address;       // jtag_uart_pipeline_bridge_m0_translator:uav_address -> jtag_uart_avalon_jtag_slave_translator:uav_address
	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_read;          // jtag_uart_pipeline_bridge_m0_translator:uav_read -> jtag_uart_avalon_jtag_slave_translator:uav_read
	wire   [3:0] jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable;    // jtag_uart_pipeline_bridge_m0_translator:uav_byteenable -> jtag_uart_avalon_jtag_slave_translator:uav_byteenable
	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid; // jtag_uart_avalon_jtag_slave_translator:uav_readdatavalid -> jtag_uart_pipeline_bridge_m0_translator:uav_readdatavalid
	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_lock;          // jtag_uart_pipeline_bridge_m0_translator:uav_lock -> jtag_uart_avalon_jtag_slave_translator:uav_lock
	wire         jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_write;         // jtag_uart_pipeline_bridge_m0_translator:uav_write -> jtag_uart_avalon_jtag_slave_translator:uav_write
	wire  [31:0] jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata;     // jtag_uart_pipeline_bridge_m0_translator:uav_writedata -> jtag_uart_avalon_jtag_slave_translator:uav_writedata
	wire   [2:0] jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount;    // jtag_uart_pipeline_bridge_m0_translator:uav_burstcount -> jtag_uart_avalon_jtag_slave_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (3),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (3),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) jtag_uart_pipeline_bridge_m0_translator (
		.clk                    (PLL_50_150_outclk0_clk),                                                          //                       clk.clk
		.reset                  (jtag_uart_pipeline_bridge_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (jtag_uart_pipeline_bridge_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (jtag_uart_pipeline_bridge_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (jtag_uart_pipeline_bridge_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (jtag_uart_pipeline_bridge_m0_byteenable),                                         //                          .byteenable
		.av_read                (jtag_uart_pipeline_bridge_m0_read),                                               //                          .read
		.av_readdata            (jtag_uart_pipeline_bridge_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (jtag_uart_pipeline_bridge_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (jtag_uart_pipeline_bridge_m0_write),                                              //                          .write
		.av_writedata           (jtag_uart_pipeline_bridge_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (jtag_uart_pipeline_bridge_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                            //               (terminated)
		.av_begintransfer       (1'b0),                                                                            //               (terminated)
		.av_chipselect          (1'b0),                                                                            //               (terminated)
		.av_lock                (1'b0),                                                                            //               (terminated)
		.uav_clken              (),                                                                                //               (terminated)
		.av_clken               (1'b1),                                                                            //               (terminated)
		.uav_response           (2'b00),                                                                           //               (terminated)
		.av_response            (),                                                                                //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                            //               (terminated)
		.av_writeresponsevalid  ()                                                                                 //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (3),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) jtag_uart_avalon_jtag_slave_translator (
		.clk                    (PLL_50_150_outclk0_clk),                                                          //                      clk.clk
		.reset                  (jtag_uart_pipeline_bridge_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (jtag_uart_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (jtag_uart_avalon_jtag_slave_address),                                             //      avalon_anti_slave_0.address
		.av_write               (jtag_uart_avalon_jtag_slave_write),                                               //                         .write
		.av_read                (jtag_uart_avalon_jtag_slave_read),                                                //                         .read
		.av_readdata            (jtag_uart_avalon_jtag_slave_readdata),                                            //                         .readdata
		.av_writedata           (jtag_uart_avalon_jtag_slave_writedata),                                           //                         .writedata
		.av_waitrequest         (jtag_uart_avalon_jtag_slave_waitrequest),                                         //                         .waitrequest
		.av_chipselect          (jtag_uart_avalon_jtag_slave_chipselect),                                          //                         .chipselect
		.av_begintransfer       (),                                                                                //              (terminated)
		.av_beginbursttransfer  (),                                                                                //              (terminated)
		.av_burstcount          (),                                                                                //              (terminated)
		.av_byteenable          (),                                                                                //              (terminated)
		.av_readdatavalid       (1'b0),                                                                            //              (terminated)
		.av_writebyteenable     (),                                                                                //              (terminated)
		.av_lock                (),                                                                                //              (terminated)
		.av_clken               (),                                                                                //              (terminated)
		.uav_clken              (1'b0),                                                                            //              (terminated)
		.av_debugaccess         (),                                                                                //              (terminated)
		.av_outputenable        (),                                                                                //              (terminated)
		.uav_response           (),                                                                                //              (terminated)
		.av_response            (2'b00),                                                                           //              (terminated)
		.uav_writeresponsevalid (),                                                                                //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                             //              (terminated)
	);

endmodule
