// soc_simple_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module soc_simple_mm_interconnect_2 (
		input  wire        PLL_50_150_outclk0_clk,                                //                              PLL_50_150_outclk0.clk
		input  wire        pio_pipeline_bridge_reset_reset_bridge_in_reset_reset, // pio_pipeline_bridge_reset_reset_bridge_in_reset.reset
		input  wire [3:0]  pio_pipeline_bridge_m0_address,                        //                          pio_pipeline_bridge_m0.address
		output wire        pio_pipeline_bridge_m0_waitrequest,                    //                                                .waitrequest
		input  wire [0:0]  pio_pipeline_bridge_m0_burstcount,                     //                                                .burstcount
		input  wire [3:0]  pio_pipeline_bridge_m0_byteenable,                     //                                                .byteenable
		input  wire        pio_pipeline_bridge_m0_read,                           //                                                .read
		output wire [31:0] pio_pipeline_bridge_m0_readdata,                       //                                                .readdata
		output wire        pio_pipeline_bridge_m0_readdatavalid,                  //                                                .readdatavalid
		input  wire        pio_pipeline_bridge_m0_write,                          //                                                .write
		input  wire [31:0] pio_pipeline_bridge_m0_writedata,                      //                                                .writedata
		input  wire        pio_pipeline_bridge_m0_debugaccess,                    //                                                .debugaccess
		output wire [1:0]  leds_s1_address,                                       //                                         leds_s1.address
		output wire        leds_s1_write,                                         //                                                .write
		input  wire [31:0] leds_s1_readdata,                                      //                                                .readdata
		output wire [31:0] leds_s1_writedata,                                     //                                                .writedata
		output wire        leds_s1_chipselect                                     //                                                .chipselect
	);

	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest;   // leds_s1_translator:uav_waitrequest -> pio_pipeline_bridge_m0_translator:uav_waitrequest
	wire  [31:0] pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata;      // leds_s1_translator:uav_readdata -> pio_pipeline_bridge_m0_translator:uav_readdata
	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess;   // pio_pipeline_bridge_m0_translator:uav_debugaccess -> leds_s1_translator:uav_debugaccess
	wire   [3:0] pio_pipeline_bridge_m0_translator_avalon_universal_master_0_address;       // pio_pipeline_bridge_m0_translator:uav_address -> leds_s1_translator:uav_address
	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_read;          // pio_pipeline_bridge_m0_translator:uav_read -> leds_s1_translator:uav_read
	wire   [3:0] pio_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable;    // pio_pipeline_bridge_m0_translator:uav_byteenable -> leds_s1_translator:uav_byteenable
	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid; // leds_s1_translator:uav_readdatavalid -> pio_pipeline_bridge_m0_translator:uav_readdatavalid
	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_lock;          // pio_pipeline_bridge_m0_translator:uav_lock -> leds_s1_translator:uav_lock
	wire         pio_pipeline_bridge_m0_translator_avalon_universal_master_0_write;         // pio_pipeline_bridge_m0_translator:uav_write -> leds_s1_translator:uav_write
	wire  [31:0] pio_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata;     // pio_pipeline_bridge_m0_translator:uav_writedata -> leds_s1_translator:uav_writedata
	wire   [2:0] pio_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount;    // pio_pipeline_bridge_m0_translator:uav_burstcount -> leds_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (4),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (4),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) pio_pipeline_bridge_m0_translator (
		.clk                    (PLL_50_150_outclk0_clk),                                                    //                       clk.clk
		.reset                  (pio_pipeline_bridge_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (pio_pipeline_bridge_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (pio_pipeline_bridge_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (pio_pipeline_bridge_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (pio_pipeline_bridge_m0_byteenable),                                         //                          .byteenable
		.av_read                (pio_pipeline_bridge_m0_read),                                               //                          .read
		.av_readdata            (pio_pipeline_bridge_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (pio_pipeline_bridge_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (pio_pipeline_bridge_m0_write),                                              //                          .write
		.av_writedata           (pio_pipeline_bridge_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (pio_pipeline_bridge_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                      //               (terminated)
		.av_begintransfer       (1'b0),                                                                      //               (terminated)
		.av_chipselect          (1'b0),                                                                      //               (terminated)
		.av_lock                (1'b0),                                                                      //               (terminated)
		.uav_clken              (),                                                                          //               (terminated)
		.av_clken               (1'b1),                                                                      //               (terminated)
		.uav_response           (2'b00),                                                                     //               (terminated)
		.av_response            (),                                                                          //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                      //               (terminated)
		.av_writeresponsevalid  ()                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (4),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) leds_s1_translator (
		.clk                    (PLL_50_150_outclk0_clk),                                                    //                      clk.clk
		.reset                  (pio_pipeline_bridge_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (pio_pipeline_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (leds_s1_address),                                                           //      avalon_anti_slave_0.address
		.av_write               (leds_s1_write),                                                             //                         .write
		.av_readdata            (leds_s1_readdata),                                                          //                         .readdata
		.av_writedata           (leds_s1_writedata),                                                         //                         .writedata
		.av_chipselect          (leds_s1_chipselect),                                                        //                         .chipselect
		.av_read                (),                                                                          //              (terminated)
		.av_begintransfer       (),                                                                          //              (terminated)
		.av_beginbursttransfer  (),                                                                          //              (terminated)
		.av_burstcount          (),                                                                          //              (terminated)
		.av_byteenable          (),                                                                          //              (terminated)
		.av_readdatavalid       (1'b0),                                                                      //              (terminated)
		.av_waitrequest         (1'b0),                                                                      //              (terminated)
		.av_writebyteenable     (),                                                                          //              (terminated)
		.av_lock                (),                                                                          //              (terminated)
		.av_clken               (),                                                                          //              (terminated)
		.uav_clken              (1'b0),                                                                      //              (terminated)
		.av_debugaccess         (),                                                                          //              (terminated)
		.av_outputenable        (),                                                                          //              (terminated)
		.uav_response           (),                                                                          //              (terminated)
		.av_response            (2'b00),                                                                     //              (terminated)
		.uav_writeresponsevalid (),                                                                          //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                       //              (terminated)
	);

endmodule
